name: CI

on:
  push:
    paths:
      - "*"
      - "src/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 21
          cache: maven

      - name: Run tests
        run: make test

      - name: Build Image
        run: make image-build